services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: apex_predict_admin
      POSTGRES_PASSWORD: Apex_predict
      POSTGRES_DB: apex_predict_db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    



volumes:
  postgres_data: